### ISSUE TITLE
OSX build failing

### ISSUE THREAD

**Issue by vidartf** [conda-forge/pythreejs-feedstock#20]
While the CI for https://github.com/conda-forge/pythreejs-feedstock/pull/17 succeeded the subsequent build from master fails for OSX: https://travis-ci.org/conda-forge/pythreejs-feedstock/builds/389298550 .

Details for posterity:
<details>
<summary>Python 2 trace</summary>
<pre>
copying build/lib/pythreejs/pythreejs.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450377932/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/pythreejs
error: [Errno 35] Resource temporarily unavailable
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/pythreejs_1528450377932/work/conda_build.sh']' returned non-zero exit status 1.
The command "conda build ./recipe -m ./.ci_support/${CONFIG}.yaml" exited with 1.
7.00s$ upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
Adding in variants from internal_defaults
Adding in variants from ./.ci_support/osx_python2.7.yaml
Attempting to finalize metadata for pythreejs
Solving environment: ...working... done
Solving environment: ...working... done
Processing pythreejs
[ERROR] File "/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py27_1.tar.bz2" does not exist
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 131, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 121, in main
    upload(cli, fname, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 68, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpavqh9v59/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py27_1.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
The command "upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml" exited with 1.
</pre>
</details>

<details>
<summary>Python 3 trace</summary>
<pre>
copying build/lib/pythreejs/math/interpolants/__init__.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
copying build/lib/pythreejs/math/interpolants/CubicInterpolant_autogen.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
copying build/lib/pythreejs/math/interpolants/DiscreteInterpolant_autogen.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
error: [Errno 35] write could not complete without blocking
copying build/lib/pythreejs/math/interpolants/LinearInterpolant_autogen.py -> /Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pythreejs/math/interpolants
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 35] write could not complete without blocking
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/pythreejs_1528450843407/work/conda_build.sh']' returned non-zero exit status 1.
The command "conda build ./recipe -m ./.ci_support/${CONFIG}.yaml" exited with 1.
7.00s$ upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
Adding in variants from internal_defaults
Adding in variants from ./.ci_support/osx_python3.5.yaml
Attempting to finalize metadata for pythreejs
Solving environment: ...working... done
Solving environment: ...working... done
Processing pythreejs
[ERROR] File "/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py35_1.tar.bz2" does not exist
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 131, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 121, in main
    upload(cli, fname, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 68, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpnfrm5mnu/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/pythreejs-1.1.0-py35_1.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
The command "upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml" exited with 1.
</pre>
</details>
<br/>
Does anybody know what could be causing this, or where the cause of the issue is (my code, travis, conda code)? I have no clue...

Ping @conda-forge/core , ref https://github.com/conda-forge/conda-forge.github.io/issues/599.

**Comment by jakirkham** [comment]
After doing a little bit of digging, this seems similar to issue ( https://github.com/conda/conda/issues/6473 ), which proposes using [this workaround]( https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959 ) to fix it. Could try adding that in before the build step just for macOS as part of `script`.

Perhaps that workaround can be integrated into `conda-build` proper. Added upstream issue ( https://github.com/conda/conda-build/issues/2961 ) to start that discussion.

Independently it appears we are not using `pip` to do the build. Not surprising as many feedstocks still need to be converted over. Still it would be good to make that switch. Would be interesting to know if that alone fixes the issue or not.

ref: https://conda-forge.org/docs/meta.html#use-pip

**Comment by vidartf** [comment]
In the workaround linked, I see this:

> I just spent a fun day figuring out that something inside "npm install ..." was switching to nonblocking mode, causing random failures further down in my build script.

As the build currently invokes npm, this might be the issue. I.e. that the setup script should switch back to blocking mode after any subprocess calls to npm. Or?

**Comment by vidartf** [comment]
> Independently it appears we are not using pip to do the build. Not surprising as many feedstocks still need to be converted over. Still it would be good to make that switch. Would be interesting to know if that alone fixes the issue or not.

It seems like switching to using pip fixed the issue: https://travis-ci.org/conda-forge/pythreejs-feedstock/builds/391168521
This would also explain why my other similar projects did not produce the error, they were all newer recipes using pip. Thanks!

**Comment by vidartf** [comment]
@jakirkham Considering that using pip fixed this, are you okay with me closing this? Any further discussion on the non-blocking parts could happen on the conda-build issue.

**Comment by jakirkham** [comment]
Was just about to ask if you had put a PR up and then saw PR ( https://github.com/conda-forge/pythreejs-feedstock/pull/21 ). Feel free to close, @vidartf. Glad to hear it is fixed. 😄
