### ISSUE TITLE
Post-link scripts fails over `numpy`  missing

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/pythreejs-feedstock#28]
The postlink script for pythreejs fails because `numpy`  is missing from the environment upon call of the script.

Since we cannot guarantee that any package is present at post-link time , and anything may be imported by the top-level `__init__.py `, I suggest that we drop post-link scripts in the pythreejs feedstock and other widget feedstocks. This has bitten us in many cases, so I don't believe we should push this as a good pattern to use moving forward.

The consequence will be that users of notebook<5.4 will need to manually enable the nbextension.

cc @jasongrout @vidartf @maartenbreddels

**Comment by vidartf** [comment]
The future is now! +1

**Comment by SylvainCorlay** [comment]
Ok. Will open a pr to the feedstock.
