### ISSUE TITLE
noarch support?

### ISSUE THREAD

**Issue by bdice** [conda-forge/pythreejs-feedstock#30]
Can this package be defined as `noarch`? I'm running Linux on a POWER9 system (`ppc64le`) and it seems I can't install this package because it's only built for `linux-64`.

https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds

From what I can tell, this package adheres to the requirements for `noarch`. Anecdotally, I've found it's slightly easier to maintain conda-forge recipes that are `noarch`.

I can make a PR with this change if desired.

**Comment by vidartf** [comment]
Given that ipywidgets is noarch, I don't see why not. PRs welcome if you are impatient :)

**Comment by bdice** [comment]
@vidartf I made a PR #31, hope that helps! :) Looks like all checks have passed. No rush, take a look whenever you have time.

PS, pythreejs is really awesome. Thanks for your work on the package. 👍
